"on":
  push:
    branches:
    - master
name: Deploy to Porter
jobs:
  porter-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2.3.4
    - name: Set Github tag
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - name: Update Porter App
      timeout-minutes: 20
      uses: porter-dev/porter-update-action@v0.26.0
      with:
        app: gin-test-hello-porter
        cluster: "83"
        host: https://dashboard.staging.getporter.dev
        namespace: default
        project: "72"
        tag: ${{ steps.vars.outputs.sha_short }}
        token: ${{ secrets.PORTER_TOKEN_PRODUCTION_72 }}
